import { ClassItem, Trainer, Schedule, MembershipPlan } from './types';

export const GYM_INFO = {
  name: '11 Fight Camp',
  tagline: 'Forge Your Strength. Master the Art of Combat.',
  subTagline: 'Sasana bela diri & combat fitness nomor satu di Pontianak. Muay Thai, Boxing, BJJ, MMA untuk pemula hingga atlet.',
  phone: '+628818124824',
  phoneFormatted: '+62 881-8124-824',
  instagram: '11fightcamp',
  instagramUrl: 'https://www.instagram.com/11fightcamp/?hl=en',
  address: 'Jl. Dr. Rubini No. 11, Akcaya, Kec. Pontianak Selatan, Kota Pontianak, Kalimantan Barat 78113',
  googleMapsUrl: 'https://maps.google.com/?q=11+Fight+Camp+Pontianak+Jl+Dr+Rubini+No+11',
  openingHours: [
    { days: 'Senin - Jumat', morning: '07:30 - 11:00', evening: '15:30 - 21:30' },
    { days: 'Sabtu', morning: '08:00 - 12:00', evening: '15:30 - 19:30' },
    { days: 'Minggu', morning: 'Tutup / Private Sesi Only', evening: 'Tutup' },
  ],
};

export const INITIAL_CLASSES: ClassItem[] = [
  {
    id: 'class-muay-thai',
    title: 'Muay Thai (The Art of 8 Limbs)',
    category: 'muay-thai',
    description: 'Seni bela diri Thailand yang memanfaatkan pukulan, tendangan, sikutan, dan lutut. Efektif membakar kalori tinggi sekaligus mengasah reflek pertahanan diri.',
    durationMinutes: 90,
    intensity: 'All Levels',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1000&q=80',
    equipmentNeeded: ['Handwrap', 'Sarung Tinju (Glove)', 'Pakaian Olahraga Nyaman'],
    benefits: ['Bakar 600-900 kcal/sesi', 'Power & Endurance', 'Teknik Striking Lengkap', 'Mental Disiplin'],
  },
  {
    id: 'class-boxing',
    title: 'Boxing & Sweet Science',
    category: 'boxing',
    description: 'Fokus pada teknik tinju murni, koordinasi gerak kaki (footwork), head movement, pukulan kombinasi, serta latihan pad work dan heavy bag.',
    durationMinutes: 75,
    intensity: 'All Levels',
    imageUrl: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1000&q=80',
    equipmentNeeded: ['Handwrap', 'Boxing Glove (12-14oz)', 'Sepatu Boxing / Running'],
    benefits: ['Kecepatan & Agility', 'Kekuatan Inti (Core)', 'Relief Stres Maksimal', 'Pertahanan Diri'],
  },
  {
    id: 'class-bjj',
    title: 'Brazilian Jiu-Jitsu (BJJ)',
    category: 'bjj',
    description: 'Seni bertarung bawah tanah (ground fighting) dan kuncian (submission). Mengedepankan teknik dan leverage agar yang lebih kecil mampu mengalahkan lawan lebih besar.',
    durationMinutes: 90,
    intensity: 'Beginner Friendly',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1000&q=80',
    equipmentNeeded: ['Gi / No-Gi Rashguard', 'Mouthguard', 'Celana Grappling'],
    benefits: ['Strategi & Problem Solving', 'Fleksibilitas Sendi', 'Submissions & Escapes', 'Low Impact Joint'],
  },
  {
    id: 'class-mma',
    title: 'MMA (Mixed Martial Arts)',
    category: 'mma',
    description: 'Integrasi striking Muay Thai/Boxing dan grappling BJJ/Wrestling di octagon. Dirancang untuk petarung modern dan mereka yang ingin tantangan tertinggi.',
    durationMinutes: 90,
    intensity: 'High Intensity',
    imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1000&q=80',
    equipmentNeeded: ['MMA Glove 4-7oz', 'Shin Guards', 'Mouthguard'],
    benefits: ['Kombinasi Seni Tempur Lengkap', 'Kesiapan Fight / Cage', 'Ketahanan Fisik Tertinggi'],
  },
  {
    id: 'class-conditioning',
    title: 'Fighter Strength & HIIT',
    category: 'conditioning',
    description: 'Latihan fungsional pembakar lemak khas petarung: kettlebell, battle rope, box jumps, tire flip, dan core circuit tanpa kontak fisik.',
    durationMinutes: 60,
    intensity: 'High Intensity',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1000&q=80',
    equipmentNeeded: ['Botol Minum', 'Handuk Olahraga', 'Sepatu Training'],
    benefits: ['Fat Loss Cepat', 'Kardiovaskular Kuat', 'Tone Otot & Stamina'],
  },
  {
    id: 'class-private',
    title: 'Private 1-on-1 Training',
    category: 'private',
    description: 'Sesi latihan privat eksklusif bersama Coach berpengalaman. Kurikulum disesuaikan dengan tujuan Anda: teknik mendalam, penurunan berat badan, atau persiapan tanding.',
    durationMinutes: 75,
    intensity: 'All Levels',
    imageUrl: 'https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=1000&q=80',
    equipmentNeeded: ['Peralatan Disediakan / Milik Sendiri'],
    benefits: ['100% Perhatian Pelatih', 'Perkembangan 3x Lebih Cepat', 'Jadwal Fleksibel', 'Analisis Teknik Real-Time'],
  },
];

export const INITIAL_TRAINERS: Trainer[] = [
  {
    id: 'trainer-1',
    name: 'Coach Kevin "The Striker"',
    role: 'Head Muay Thai Coach',
    specialty: 'Muay Thai & K1 Striking',
    bio: 'Atlet kompetisi striking dengan pengalaman lebih dari 8 tahun melatih ratusan praktisi dari pemula hingga juara regional.',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    instagram: '11fightcamp',
    achievements: ['Regional Muay Thai Champion', 'Certified Striking Instructor', 'Head Coach 11FC'],
  },
  {
    id: 'trainer-2',
    name: 'Coach David "The Anaconda"',
    role: 'BJJ & MMA Specialist',
    specialty: 'Brazilian Jiu-Jitsu (BJJ) & Cage Wrestling',
    bio: 'Praktisi BJJ dengan pemahaman mendalam kuncian sendi, takedown, dan transisi pertarungan bawah yang aman bagi pemula.',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    instagram: '11fightcamp',
    achievements: ['BJJ Purple Belt Podiums', 'Grappling State Invitational Finalist', 'Submission Specialist'],
  },
  {
    id: 'trainer-3',
    name: 'Coach Aris "Thunder"',
    role: 'Boxing & Conditioning Coach',
    specialty: 'Western Boxing & High Intensity Conditioning',
    bio: 'Fokus pada kerapian pukulan jab-cross-hook, reflek menghindar, serta metode penurunan berat badan atletis.',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&q=80',
    instagram: '11fightcamp',
    achievements: ['Amateur Boxing Veteran', 'Strength & Conditioning Specialist', 'Body Transformation Mentor'],
  },
];

export const INITIAL_SCHEDULES: Schedule[] = [
  // Senin (1)
  {
    id: 'sch-mon-1',
    classId: 'class-muay-thai',
    trainerId: 'trainer-1',
    dayOfWeek: 1,
    startTime: '16:30',
    endTime: '18:00',
    maxCapacity: 15,
    price: 75000,
    isActive: true,
  },
  {
    id: 'sch-mon-2',
    classId: 'class-boxing',
    trainerId: 'trainer-3',
    dayOfWeek: 1,
    startTime: '19:00',
    endTime: '20:30',
    maxCapacity: 12,
    price: 75000,
    isActive: true,
  },
  // Selasa (2)
  {
    id: 'sch-tue-1',
    classId: 'class-bjj',
    trainerId: 'trainer-2',
    dayOfWeek: 2,
    startTime: '16:30',
    endTime: '18:00',
    maxCapacity: 14,
    price: 80000,
    isActive: true,
  },
  {
    id: 'sch-tue-2',
    classId: 'class-conditioning',
    trainerId: 'trainer-3',
    dayOfWeek: 2,
    startTime: '19:00',
    endTime: '20:15',
    maxCapacity: 16,
    price: 65000,
    isActive: true,
  },
  // Rabu (3)
  {
    id: 'sch-wed-1',
    classId: 'class-muay-thai',
    trainerId: 'trainer-1',
    dayOfWeek: 3,
    startTime: '16:30',
    endTime: '18:00',
    maxCapacity: 15,
    price: 75000,
    isActive: true,
  },
  {
    id: 'sch-wed-2',
    classId: 'class-mma',
    trainerId: 'trainer-2',
    dayOfWeek: 3,
    startTime: '19:00',
    endTime: '20:30',
    maxCapacity: 12,
    price: 85000,
    isActive: true,
  },
  // Kamis (4)
  {
    id: 'sch-thu-1',
    classId: 'class-boxing',
    trainerId: 'trainer-3',
    dayOfWeek: 4,
    startTime: '16:30',
    endTime: '18:00',
    maxCapacity: 12,
    price: 75000,
    isActive: true,
  },
  {
    id: 'sch-thu-2',
    classId: 'class-bjj',
    trainerId: 'trainer-2',
    dayOfWeek: 4,
    startTime: '19:00',
    endTime: '20:30',
    maxCapacity: 14,
    price: 80000,
    isActive: true,
  },
  // Jumat (5)
  {
    id: 'sch-fri-1',
    classId: 'class-muay-thai',
    trainerId: 'trainer-1',
    dayOfWeek: 5,
    startTime: '16:30',
    endTime: '18:00',
    maxCapacity: 15,
    price: 75000,
    isActive: true,
  },
  {
    id: 'sch-fri-2',
    classId: 'class-conditioning',
    trainerId: 'trainer-3',
    dayOfWeek: 5,
    startTime: '19:00',
    endTime: '20:15',
    maxCapacity: 16,
    price: 65000,
    isActive: true,
  },
  // Sabtu (6)
  {
    id: 'sch-sat-1',
    classId: 'class-muay-thai',
    trainerId: 'trainer-1',
    dayOfWeek: 6,
    startTime: '09:00',
    endTime: '10:30',
    maxCapacity: 15,
    price: 75000,
    isActive: true,
  },
  {
    id: 'sch-sat-2',
    classId: 'class-mma',
    trainerId: 'trainer-2',
    dayOfWeek: 6,
    startTime: '16:00',
    endTime: '17:30',
    maxCapacity: 12,
    price: 85000,
    isActive: true,
  },
];

export const MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: 'drop-in',
    title: 'Single Session (Drop-in)',
    subtitle: 'Cocok untuk coba pertama kali atau jadwal fleksibel',
    price: 75000,
    period: 'per sesi',
    features: [
      'Akses 1 sesi kelas reguler apa saja',
      'Peminjaman sarung tinju gratis untuk first-timer',
      'Bimbingan langsung dari coach di kelas',
      'Fasilitas shower, loker, dan air minum',
    ],
  },
  {
    id: 'pack-10',
    title: '10 Sessions Pass',
    subtitle: 'Paling populer untuk rutin latihan mingguan',
    price: 650000,
    period: 'berlaku 45 hari',
    isPopular: true,
    badge: 'Best Value',
    features: [
      'Hemat Rp 100.000 dibanding drop-in',
      'Bebas pilih kelas: Muay Thai, Boxing, BJJ, MMA',
      'Bisa booking jadwal fleksibel kapan saja',
      'Masa aktif 45 hari sejak sesi pertama',
      'Prioritas slot booking kelas favorit',
    ],
  },
  {
    id: 'unlimited-monthly',
    title: 'Monthly Unlimited',
    subtitle: 'Untuk kamu yang berkomitmen serius transformasi',
    price: 900000,
    period: 'per bulan',
    badge: 'Pro Fighter',
    features: [
      'Akses tanpa batas ke SEMUA kelas reguler',
      'Bisa latihan setiap hari (Senin - Sabtu)',
      'Free konsultasi program & nutrisi dasar',
      'Diskon 15% untuk official merchandise 11FC',
      'Akses area gym saat jam operasional',
    ],
  },
  {
    id: 'private-pack',
    title: 'Private 1-on-1 (5 Sessions)',
    subtitle: 'Program eksklusif dengan Coach pilihan',
    price: 1100000,
    period: '5 sesi privat',
    features: [
      '5 sesi privat intensif 75 menit',
      'Jadwal fleksibel (pagi, siang, malam)',
      'Analisis teknik detail & pad work eksklusif',
      'Fokus personal: kurangi berat badan / teknik bertarung',
    ],
  },
];

export const TESTIMONIALS = [
  {
    name: 'Dimas Kurniawan',
    role: 'Member sejak 2024',
    text: 'Awalnya gabung cuma buat turunin berat badan, tapi sekarang malah ketagihan Muay Thai di 11 Fight Camp. Coach-coachnya ramah buat pemula dan tekniknya beneran diajarin detail!',
    rating: 5,
    classTag: 'Muay Thai',
  },
  {
    name: 'Sarah Stephanie',
    role: 'Member Boxing',
    text: 'Vibe camp-nya keren banget, safe space buat cewek yang mau belajar boxing dan kardio. Latihan 1 jam keringatnya kayak lari 10 km. Sangat recommended buat warga Pontianak!',
    rating: 5,
    classTag: 'Boxing',
  },
  {
    name: 'Rian Pratama',
    role: 'MMA Practitioner',
    text: 'Camp bela diri paling lengkap di Pontianak. Ada BJJ dan MMA dengan instruktur yang paham banget teknik ground dan striking. Jadwal kelasnya juga teratur.',
    rating: 5,
    classTag: 'BJJ & MMA',
  },
];
